version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=recipe_app
      - DB_USER=user
      - DB_PASS=password01

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=recipe_app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password01

  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=igorjacon90@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password01
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  pgadmin-data:
